name: Tesis
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py39h5769e4c_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - aom=3.9.1=he0c23c2_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - blas=1.0=mkl
  - blosc=1.21.6=hfd34d9b_1
  - bottleneck=1.4.2=py39hc99e966_0
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.10.5=py39haa95532_0
  - cgal-cpp=6.0.2=hc4f255e_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h2b77a98_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hcfcfb64_0
  - double-conversion=3.3.1=he0c23c2_0
  - eigen=3.4.0=h477610d_1
  - expat=2.7.1=h8ddb27b_0
  - ffmpeg=7.1.1=gpl_hc27df84_704
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.1=py39h5769e4c_0
  - freeglut=3.2.2=he0c23c2_3
  - freeimage=3.18.0=hf09a29c_23
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - frozenlist=1.7.0=py39h6d15d50_0
  - gdk-pixbuf=2.42.12=hed59a49_0
  - geos=3.13.1=h9ea8674_0
  - gl2ps=1.4.2=had7236b_1
  - gmp=6.3.0=hfeafd45_2
  - graphite2=1.3.14=hac47afa_2
  - gst-plugins-base=1.24.12=h91a6125_1
  - gstreamer=1.24.12=hfb93a4f_1
  - gstreamer-orc=0.4.41=ha00e802_0
  - harfbuzz=11.0.0=h9e37d49_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.6=nompi_he30205f_103
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - ifcopenshell=0.8.3.post1=py39h4477386_1
  - imath=3.2.1=h1608b31_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jasper=4.2.8=h8ad263b_0
  - jsoncpp=1.9.6=hda1637e_1
  - jxrlib=1.1=hcfcfb64_3
  - kiwisolver=1.4.7=py39h2b77a98_0
  - krb5=1.21.3=hdf4eb48_0
  - lame=3.100=hcfcfb64_1003
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.4=h20038f6_0
  - libblas=3.9.0=20_win64_mkl
  - libboost=1.88.0=h9dfe17d_5
  - libboost-devel=1.88.0=h1c1089f_5
  - libboost-headers=1.88.0=h57928b3_5
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.9.0=20_win64_mkl
  - libclang13=21.1.4=default_ha2db4b5_0
  - libcurl=8.16.0=h43ecb02_0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libglib=2.84.0=h7025463_0
  - libgomp=15.2.0=h1383e82_7
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=20_win64_mkl
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libnetcdf=4.9.2=nompi_ha45073a_118
  - libogg=1.3.5=h2466b09_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h7351971_1
  - libraw=0.21.4=h866491b_0
  - librsvg=2.58.4=h5ce5fed_3
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtheora=1.1.1=hc70643c_1006
  - libtiff=4.7.1=h550210a_0
  - libusb=1.0.29=h1839187_0
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=20.1.8=h29ce207_0
  - loguru=0.7.3=pyh7428d3b_0
  - lz4-c=1.10.0=h2466b09_1
  - matplotlib=3.9.2=py39haa95532_1
  - matplotlib-base=3.9.2=py39he19b0ae_1
  - mkl=2023.2.0=h6a75c08_50497
  - mkl-service=2.4.0=py39h827c3e9_2
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - mpfr=4.2.1=hbc20e70_3
  - msgpack-python=1.1.1=py39h2b77a98_0
  - multidict=6.6.3=py39h5769e4c_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h5112557_1
  - numexpr=2.10.1=py39h4cd664f_0
  - numpy=2.0.2=py39h055cbcc_0
  - numpy-base=2.0.2=py39h65a83cf_0
  - occt=7.9.0=all_h5eb6187_204
  - openexr=3.3.5=hed76565_1
  - openh264=2.6.0=hb17fa0b_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py39ha5e6156_0
  - pango=1.56.3=h0c53d3b_1
  - pcre2=10.44=h99c9b8b_2
  - pillow=11.3.0=py39hbad85af_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h5112557_1
  - ply=3.11=py39haa95532_0
  - proj=9.6.2=h7990399_2
  - propcache=0.3.1=py39hf73967f_0
  - pthread-stubs=0.4=h0e40799_1002
  - pugixml=1.15=h372dad0_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyqt=5.15.10=py39h5da7b33_1
  - pyqt5-sip=12.13.0=py39h827c3e9_1
  - python=3.9.24=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pythonocc-core=7.9.0=all_h3e79b3e_200
  - pytz=2025.2=py39haa95532_0
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.15=h9151539_3
  - qt6-main=6.9.0=h83cda92_0
  - rapidjson=1.1.0.post20240409=he0c23c2_2
  - sdl2=2.32.56=h5112557_0
  - sdl3=3.2.26=h5112557_0
  - setuptools=72.1.0=py39haa95532_0
  - shapely=2.0.7=py39h3a0aaa4_1
  - sip=6.7.12=py39h5da7b33_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_0
  - sqlite=3.50.2=hda9a48d_1
  - svgwrite=1.4.3=pyhd8ed1ab_1
  - svt-av1=3.0.2=he0c23c2_0
  - tbb=2021.13.0=h18a62a1_3
  - tbb-devel=2021.13.0=h4eb897c_3
  - tk=8.6.15=hf199647_0
  - tomli=2.2.1=py39haa95532_0
  - tornado=6.5.1=py39h827c3e9_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=16.0.0=py39ha55e580_0
  - utfcpp=4.0.8=h57928b3_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - vtk=9.4.2=hbf458c8_3
  - vtk-base=9.4.2=py39ha1f65a8_0
  - wheel=0.45.1=py39haa95532_0
  - win32_setctime=1.2.0=pyhd8ed1ab_0
  - wslink=2.4.0=pyhd8ed1ab_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - yarl=1.20.1=py39hf73967f_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - charset-normalizer==3.4.4
      - dacite==1.9.2
      - filetype==1.2.0
      - flatbuffers==25.9.23
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.14.0
      - imagehash==4.3.1
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - keras==3.10.0
      - lark==1.3.1
      - libclang==18.1.1
      - llvmlite==0.43.0
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - minify-html==0.18.1
      - ml-dtypes==0.5.3
      - multimethod==1.12
      - namex==0.1.0
      - networkx==3.2.1
      - numba==0.60.0
      - opt-einsum==3.4.0
      - optree==0.17.0
      - patsy==1.0.2
      - phik==0.12.5
      - protobuf==6.33.0
      - puremagic==1.30
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygments==2.19.2
      - pywavelets==1.6.0
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - statsmodels==0.14.5
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typeguard==4.4.4
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - visions==0.8.1
      - werkzeug==3.1.3
      - wordcloud==1.9.4
      - wrapt==2.0.0
      - ydata-profiling==4.17.0
prefix: C:\Users\Laila\.conda\envs\Tesis
